### ISSUE TITLE
No me sale la opción de "Add folder to Workspace"

### ISSUE THREAD

**Issue by ghost** [hhkaos/cursohtml5desdecero#17]
Hola

Es un gusto haber encontrado el curso y estar acá, es el mejor que he visto hasta el momento.

Con respecto a mi problema, en la sección de Configuración (Chrome DevTools 1.4) que dice:

Ahora vamos a ver cómo podemos configurar Google Chrome para poder modificar ficheros
que se encuentren en nuestro disco duro.
Para hacer esto usaremos los "Workspaces", estos nos permitirán realizar cambios
persistentes en nuestro código sin tener que ejecutar otro editor de código.
Para ello vamos a seguir los siguientes pasos:
1. Creamos una carpeta (de prueba) en nuestro disco duro (por ejemplo "html").
2. Creamos un fichero vacío dentro de la carpeta llamado: "index.html"
3. Abrimos el fichero con Google Chrome
4. Abrimos las DevTools y nos vamos a la pestaña "Sources"
5. Hacemos clic en el panel izquierdo sobre la ruta del directorio y seleccionamos "Add
Folder to Workspace"

En el punto 5, al hacer click derecho en la ruta del directorio no me salta esa opción. He buscado hacer esto de otra forma y encontré que se puede desde la misma configuración de DevTools, Workspace, pero hasta ahí me quedo, ya que los pasos siguientes no sé como hacerlo, que son:

Ahora tenemos que "mapear" (vincular) el recurso que ha obtenido el navegador con el
fichero del disco duro que queremos modificar (osea, con él mismo), para ello:
1. Hacemos clic con el botón derecho sobre el nombre del fichero (index.html que cuelga
de "file://")
2. Elegimos la opción "Map to File System Resource":

Nuevamente no me salta esa opción.

He comprobado que mi navegador Chrome este actualizado, esta es versión:
Google Chrome está actualizado
Versión 65.0.3325.181 (Build oficial) (32 bits)

Agradecería un montón que me ayuden, me parece importante seguir con este punto y poder avanzar con el resto.

Un saludo.

**Comment by hhkaos** [comment]
Buenas @Parqvet ! gracias por avisarme. Ahora mismo dispongo de poco tiempo para verlo por mi mismo, pero... ¿has comprobado si siguiendo esta guía lo consigues?: https://developers.google.com/web/tools/setup/setup-workflow

Un abrazo y suerte!
