### ISSUE TITLE
Soy nuevo tengo dudas

### ISSUE THREAD

**Issue by HumorPc** [hhkaos/cursohtml5desdecero#19]
Hola. Soy nuevo en el curso y me gustaría saber cuándo se envían los video tutoriales y los ejercicios y cuando serían las videoconferencias. Gracias y un saludo. Creo que tendré mas dudas tendré durante el curso las preguntaré por aquí😅

**Comment by hhkaos** [comment]
Buenas @HumorPc , me temo que actualmente no puedo comprometerme con una fecha ya que hace tiempo tuve que pausar este proyecto, pero intentaré responder a cualquier duda que pueda surgirte.

Un abrazo

**Comment by HumorPc** [comment]
> Buenas @HumorPc , me temo que actualmente no puedo comprometerme con una fecha ya que hace tiempo tuve que pausar este proyecto, pero intentaré responder a cualquier duda que pueda surgirte.
> 
> Un abrazo

Muchas gracias. Cuando tengas tiempo reanudalo es muy bueno este curso. Ánimo con tus proyectos

**Comment by hhkaos** [comment]
Gracias e igualmente!. La verdad es que ganas no me faltan ^_^, intentaré buscarme una excusa para retomarlo :wink: .
